buzinas/tslint-eslint-rules

README.md
eslint_tslint.json
package.json
src/rules/noControlRegexRule.ts
src/rules/noEmptyCharacterClassRule.ts
src/rules/noInnerDeclarationsRule.ts
src/rules/noInvalidRegexpRule.ts
src/rules/noRegexSpacesRule.ts
src/test/rules/noControlRegexRuleTests.ts
src/test/rules/noEmptyCharacterClassRuleTests.ts
src/test/rules/noRegexSpacesRuleTests.ts

Added no-regex-spaces rule (c92f89e31a10eb97660fd2310ec6718fcab3b3b4)
Added no-empty-character rule (1eb34253bc16ceb05c061fa5de0dd5d2d8f9054b)
Added no-control-regex rule (17c66cf8bf0590d1a138326ef54c0c10a8cbd71d)
Improved other regex rules.

New regex rules

---

README.md

You meant `tslint.json` right?

tsconfig.json => tslint.json

---

src/rules/noConstantConditionRule.ts
src/test/rules/noConstantConditionRuleTests.ts

fix for issue #61: no-constant-condition: Error is thrown for any negated expression

---

README.md

Added missing rules from http://eslint.org/docs/rules/.  Deleted rules that have been removed.  Also updated a few existing rules.

[docs] updated README.md to match rules list on eslint.org

---

src/rules/braceStyleRule.ts
src/test/rules/braceStyleRuleTests.ts

This will fail until https://github.com/buzinas/tslint-eslint-rules/pull/101 is merged. `brace-style` tests pass (at least locally 😄).

[bug] fixed brace-style rule (closes #93)

---

.travis.yml
package.json
src/readme/fetch.ts
src/readme/index.ts
src/rules/noDuplicateCaseRule.ts
src/rules/noExtraBooleanCastRule.ts
src/rules/noExtraSemiRule.ts
src/rules/validJsdocRule.ts
tsconfig.json

Closes https://github.com/buzinas/tslint-eslint-rules/issues/124.

Use `es5` as the TypeScript target

---

gulpfile.js
src/readme/rules.ts

A few fixes were not included since the last revert. The readme file is now generated the same way every time. I updated the rules.ts file to reflect the changes made directly to the readme.

[docs:readme] updating main ts file so that readme is properly generated

---

README.md
src/docs/rules/terArrowBodyStyleRule.md
src/readme/rules.ts
src/rules/arrayBracketSpacingRule.ts
src/rules/terArrowBodyStyleRule.ts
src/test/rules/ruleTester.ts
src/test/rules/terArrowBodyStyleRuleTests.ts
tslint_eslint_rules.json

Added the rule to self-lint our files. Only found 2 places where style was not followed (using as-needed).

[feat] added ter-arrow-body-style

---

CHANGELOG.md
package.json

@jmlopez-rod Could we have a new version published with the fix in #155?

[docs] v3.2.1

---

src/rules/terArrowBodyStyleRule.ts
src/rules/terArrowParensRule.ts
src/rules/terMaxLenRule.ts

- Use the getSkipEndFromStart method
- Fix visitArrowFunction function usage

Fix typescript build errors

---

.bash_scripts/release.sh
README.md
package.json
src/docs/rules/arrayBracketSpacingRule.md
src/docs/rules/terPreferArrowCallbackRule.md
src/readme/rules.ts
src/rules/arrayBracketSpacingRule.ts
src/test/rules/arrayBracketSpacingRuleTests.ts

This PR is not ready to be merged in yet. It has a fix for issue #162, all the tests from eslint and the fixers. What remains to be done is to generate the documentation. For now I'll leave it open for code review.

[update] array-bracket-spacing

---

package.json
src/docs/rules/sortImportsRule.md
src/docs/rules/validJsdocRule.md
src/readme/rules.ts
src/rules/validJsdocRule.ts
src/test/rules/validJsdocRuleTests.ts
src/tools/newRule.ts

Fixing a current bug and adding 2 options to the rule.

[fix] valid-jsdoc

---

README.md
src/readme/rules.ts

[docs] linked no-new ESLint rule with no-unused-expression TSLint rule

---

README.md
src/docs/rules/terNoMixedSpacesAndTabsRule.md
src/readme/rules.ts
src/rules/terNoMixedSpacesAndTabsRule.ts
src/test/rules/terNoMixedSpacesAndTabsRuleTests.ts

Implemented no-mixed-spaces-and-tabs rule.

---

src/docs/rules/terNoTabsRule.md
src/rules/terNoTabsRule.ts

Used function instead of class
Fixed a typo in the documentation

[perf] improved ter-no-tabs rules

---

src/rules/spaceInParensRule.ts
src/test/rules/spaceInParensRuleTests.ts

Default option of "space-in-parens" rule has been changed to the expected value "never". Corresponding tests have been added.
Closes #305

[bug] fixed default option of "space-in-parens" (closes #305)

---

src/docs/rules/objectCurlySpacingRule.md
src/rules/objectCurlySpacingRule.ts
src/test/rules/objectCurlySpacingRuleTests.ts

My first time working with linting rules, so I hope I've done it right!
Also I had to amend some of the commented out tests, can someone please check they are correct?

[feat] Add options for object-curly-spacing rule

---

src/rules/terPaddedBlocksRule.ts
src/test/rules/terPaddedBlocksRuleTests.ts

I fixed the bugs present in the rule and wrote the fixer. I gave it a try in a project containing several hundred of files that would give false positive with the rule.
The settings used was `never`. The rule fixed the issues and now there is no reporting.

[feat] padded blocks fixer

---

src/readme/rules.ts

[fix] tslintRule of 'block-scoped-var'

---

.travis.yml
package.json
src/rules/noInnerDeclarationsRule.ts
src/rules/noMultiSpacesRule.ts
src/rules/spaceInParensRule.ts
src/rules/terIndentRule.ts
src/rules/terMaxLenRule.ts
src/rules/terPreferArrowCallbackRule.ts
src/test/rules/noMultiSpacesRuleTests.ts
src/test/rules/terIndentRuleTests.ts
src/test/rules/terMaxLenRuleTests.ts
src/test/rules/terNoSelfCompareRuleTests.ts
yarn.lock

After this there seems to be some issues with the ter-max-len rule only.
Only opening the PR to verify that travis is working properly with yarn.

[chore] updating to typescript 3.0

---

README.md

[docs] improved README.md file (discussed in #214)
