- src/rules/noUnexpectedMultilineRule.ts
- src/test/rules/noUnexpectedMultilineRuleTests.ts
Fixes #63.  Also adds support for similar situations with template tags (see http://eslint.org/docs/rules/no-unexpected-multiline).
Note: I modified the implementation of this rule fairly heavily in order to more closely align with the implementation of the corresponding eslint rule: https://github.com/eslint/eslint/blob/master/lib/rules/no-unexpected-multiline.js.
> Fix for #63: no-unexpected-multiline issue

- src/rules/validJsdocRule.ts
Currently we run into an infinite loop when calling `ValidJsdocWalker::visitClassExpression`. This method cannot be private since `Lint.SkippableTokenAwareRuleWalker` does not define it as private.
Inside `visitClassExpression` we have a call to `super.visitNode`. This will excute the `Lint.SkippableTokenAwareRuleWalker.visitNode` method which has this code:
```typescript
case ts.SyntaxKind.ClassExpression:
this.visitClassExpression(node);
break;
```
And what will be called with `this.visitClassExpression`? the one in `Lint.SkippableTokenAwareRuleWalker` or `ValidJsdocWalker`? Since the one who was calling it was `ValidJsdocWalker` we end up calling the one function we overwrote, that is
```typescript
private visitClassExpression(node: ts.ClassExpression) {
this.startFunction(node); …
```
> [bug] fixed valid-jsdoc rule (closes #100)

- src/rules/blockSpacingRule.ts
This happens when i open a `{`
> Fixes: TypeError: Cannot read property 'getChildCount' of undefined

- src/rules/handleCallbackErrRule.ts
Closes https://github.com/buzinas/tslint-eslint-rules/issues/90.
> Fix `validateReferenceForVariable` call

- src/rules/noInnerDeclarationsRule.ts
- src/test/rules/noInnerDeclarationsRuleTests.ts
As far as I can tell, the rule about declaring nested functions is as follows:
In strict mode, function declarations cannot be nested inside a statement or block. They may only appear at the top level or directly inside a function body.
Thus, if you declare
```TypeScript
namespace MyNamespace {
function MyHelperFunction() {
console.log("This _should_ be allowed.");
}
}
```
it will be compiled into something that looks vaguely like this (depending on your module output setting)
```JavaScript
var MyNamespace;
(function (MyNamespace) {
function MyHelperFunction() {
console.log("This _should_ be allowed.");
}
})(MyNamespace || (MyNamespace = {}));
```
This, therefore, does not violate the rule about nested functions, but the linter still marks it as invalid.  I propose we add …
> [fix] add namespaces as valid location for function declaration

- .gitignore
- README.md
- gulpfile.js
- package.json
- src/rules/objectCurlySpacingRule.ts
- src/test/rules/objectCurlySpacingRuleTests.ts
- tslint.json
This PR adds the `object-curly-spacing` rules according to specifications from [eslint](http://eslint.org/docs/rules/object-curly-spacing.html). The rule and test files have have been added and the README file has been updated to show that it is no longer in the TODO list.
Several other changes have been made in order to improve the developing experience.
- **No longer running all the tests to check if the rule in development works**:
By default `gulp test` will run all the tests that it can find. We can now target a particular
test by using the `single` argument as explained in the README: `gulp test --single rule-name`.
- **Transpile files even if linting fails**:
When running the tests we always run the build task which depends on the linting task.
Sometimes we may encounter linting …
> Object curly spacing

- README.md
- src/readme/rules.ts
Matched a few rules to the ones tslint now supports. Removed the usage for the rules that are supported natively since we are now providing a link to the tslint rule.
> [docs] updates

- src/rules/noConstantConditionRule.ts
- src/rules/noExAssignRule.ts
- src/support/token.ts
- src/test/rules/noExAssignRuleTests.ts
Moves the `isAssignmentToken` function into a `support` folder for code reuse.
Closes https://github.com/buzinas/tslint-eslint-rules/issues/118.
> Fix `no-ex-assign` rule on non-assignment ops

- src/rules/handleCallbackErrRule.ts
Continued from https://github.com/buzinas/tslint-eslint-rules/pull/121. This isn't really an urgent patch, since it's unlikely to hit the existing edgecases around treating a random string as a regexp, but this makes it consistent again with ESLint's handling which does a direct string check when not "not a pattern".
> Tidy up error arg check for `handle-callback-err`

- src/rules/handleCallbackErrRule.ts
- src/test/rules/handleCallbackErrRuleTests.ts
The previous code only worked on function declarations, which is by far the least used syntax when it comes to callback handling. I updated the rule to also check function expressions and arrow functions.
> Refactor the `handle-callback-err` rule

- README.md
Found some typos and wrong links on README.
I think the only 'polemic' change might be the mapping between `prefer-arrow-callback` and `only-arrow-functions`, but I do think they kind of serve the same purpose.
Please let me know what you think!
Thanks
> Rules matching on README.md

- README.md
- package.json
- src/docs/rules/terIndentRule.md
- src/readme/rules.ts
- src/rules/terIndentRule.ts
- src/test/fixtures/indent-invalid.txt
- src/test/rules/helper.ts
- src/test/rules/terIndentRuleTests.ts
This is a direct port of eslint `indent` rule. As such, it only seems to cover the basics of es6, that is, there is nothing on decorators.
A few modifications were done to the test helpers to facilitate creating tests for the rule.
> [feat] ter-indent (closes #74)

- README.md
- src/docs/rules/terIndentRule.md
- src/docs/rules/terMaxLenRule.md
- src/readme/index.ts
- src/readme/rules.ts
- src/rules/terIndentRule.ts
- src/rules/terMaxLenRule.ts
- src/test/rules/terMaxLenRuleTests.ts
Please merge the `ter-indent` PR before doing a code review on this one. This PR is a branch of the other one since I needed the modifications to the test helper file.
In this PR I have generated the documentation for `ter-max-len` and `ter-indent` from the rule metadata. This means that we now only have to worry about keeping the rule up to date and the documentation will reflect it. We can of course still add more content to the documentation if we want (special notes perhaps that may not be relevant to rule file perhaps).
> [feat] added ter-max-len

- src/rules/terMaxLenRule.ts
- src/test/rules/terMaxLenRuleTests.ts
Fixing issues with IDEs being not able to report a failure due to the missing rule name. This also fixes the failure message reporting the incorrect line number.
> [fix] ter-max-len

- gulpfile.js
- src/docs/rules/terIndentRule.md
- src/rules/noControlRegexRule.ts
- src/rules/noInvalidRegexpRule.ts
- src/rules/terIndentRule.ts
- src/test/rules/helper.ts
- src/test/rules/ruleTester.ts
- src/test/rules/terIndentRuleTests.ts
- src/test/rules/terMaxLenRuleTests.ts
- tslint_eslint_rules.json
The RuleTester helper has been updated to allow us to run groups of tests or a single test within a group (More to be explained in another PR).
Several updates have been done to the `ter-indent` rule. Bug fixes dealing with try/catch blocks and return statements as well as the addition of the `CallExpression` option.
> [update-fixes] ter-indent

- src/docs/rules/handleCallbackErrRule.md
- src/readme/rules.ts
- src/rules/handleCallbackErrRule.ts
- src/test/rules/handleCallbackErrRuleTests.ts
The current code for the rule as it stands has a bug. The line
```ts
const highlights = this.languageService.getDocumentHighlights(fileName, parameter.pos, [fileName]);
```
should be
```ts
const highlights = this.languageService.getDocumentHighlights(fileName, parameter.name.getStart(), [fileName]);
```
Making that change fixes issue #146. In this PR however, I have removed the usage of the languageService. Each call to`getDocumentHighlights` triggers a function which will search for the parameter in the document tree. The change I made is based on the `prefer-arrow-function` rule which keeps track of each function scope to determine if we make use of the error parameter. Based on some simple comparisons as noted on the issue we do get some performance with this change.
> [fix] handle-callback-err (closes #146)

- CONTRIBUTING.md
- src/docs/rules/arrayBracketSpacingRule.md
- src/docs/rules/blockSpacingRule.md
- src/docs/rules/braceStyleRule.md
- src/docs/rules/handleCallbackErrRule.md
- src/docs/rules/noConstantConditionRule.md
- src/docs/rules/noControlRegexRule.md
- src/docs/rules/noDuplicateCaseRule.md
- src/docs/rules/noEmptyCharacterClassRule.md
- src/docs/rules/noExAssignRule.md
- src/docs/rules/noExtraBooleanCastRule.md
- src/docs/rules/noExtraSemiRule.md
- src/docs/rules/noInnerDeclarationsRule.md
- src/docs/rules/noInvalidRegexpRule.md
- src/docs/rules/noIrregularWhitespaceRule.md
- src/docs/rules/noMultiSpacesRule.md
- src/docs/rules/noRegexSpacesRule.md
- src/docs/rules/noSparseArraysRule.md
- src/docs/rules/noUnexpectedMultilineRule.md
- src/docs/rules/objectCurlySpacingRule.md
- src/docs/rules/terArrowBodyStyleRule.md
- src/docs/rules/terArrowParensRule.md
- src/docs/rules/terArrowSpacingRule.md
- src/docs/rules/terIndentRule.md
- src/docs/rules/terMaxLenRule.md
- src/docs/rules/terPreferArrowCallbackRule.md
- src/docs/rules/useIsnanRule.md
- src/docs/rules/validJsdocRule.md
- src/docs/rules/validTypeofRule.md
- src/readme/index.ts
Using a badge for them look nicer. I was intending on making a footer for the page but this probably won't look so good with the current documentation we have. I might do it in the future.
> [docs] moving rule/test source links to the header

- src/rules/terIndentRule.ts
- src/test/rules/terIndentRuleTests.ts
It appears that jsdoc blocks before variable declarations break the `ter-indent` rule when using TypeScript 2.1.
Output:
```  1) ter-indent should force a certain indentation number:
TypeError: Cannot read property 'getEnd' of undefined
at IndentWalker.getLineAndCharacter (dist/rules/terIndentRule.js:215:41)
at IndentWalker.getLine (dist/rules/terIndentRule.js:220:21)
at IndentWalker.visitVariableStatement (dist/rules/terIndentRule.js:753:36)
at IndentWalker.SyntaxWalker.visitNode (node_modules/tslint/lib/language/walker/syntaxWalker.js:502:22)
at node_modules/tslint/lib/language/walker/syntaxWalker.js:517:63
at visitEachNode (node_modules/typescript/lib/typescript.js:13907:30)
at Object.forEachChild (node_modules/typescript/lib/typescript.js:14078:24)
at …
```
> [bug] fixed ter-indent rule for variable declarations with jsdoc

- src/rules/terIndentRule.ts
- src/test/rules/terIndentRuleTests.ts
While fixing this issue I also noticed that the closing bracket was not
being checked for classes, interfaces and type literals. This has been
fixed and some tests modified to trigger the errors.
> [fix] validate interfaces (closes #158)

- README.md
- src/docs/rules/useIsnanRule.md
- src/readme/rules.ts
- src/readme/unusedTSLintRules.json
When trying to migrate our eslint config to tslint, I noticed that the README is not up to date.
> Fix/add some tslint-provided rules in README

- .travis.yml
TSLint only supports node >=4.1.2.
> [chore] dropping support for node 0.10

- README.md
- index.js
- package.json
Supports extending configurations that use these rules. See #165 for more information.
This doesn't enforce any defaults for rules, although that's possible.
> [feat] exported a configuration from this package (closes #165)

- src/rules/objectCurlySpacingRule.ts
- src/test/rules/helper.ts
- src/test/rules/objectCurlySpacingRuleTests.ts
With this you can run `tslint` with `--fix` option and all curly braces paddings will be fixed.
> [feat] Add auto fix feature to object-curly-spacing rule

- src/rules/terPreferArrowCallbackRule.ts
With the update to typescript 2.2 the tree structure changed and now we
have the `MetaProperty`. I’m still leaving the old format for backwards
compatibility with typescript < 2.2.
> [fix] ter-prefer-arrow-callback broken test

- package.json
Some of the rules now implement fixers which depend on the method
`createFix` which was introduced in
https://github.com/palantir/tslint/commit/e933f7d85b120041b64c5ce7edcfbb
df80e57926.
> [fix] project requires tslint >= 4.3.0

- src/docs/rules/sortImportsRule.md
- src/readme/rules.ts
- src/rules/sortImportsRule.ts
- src/test/rules/sortImportsRuleTests.ts
This is a new rule that enforces import sorting in the same way that ESLint does, rather than TSLint's ordered-imports rule that really only checks imported member sorts.
> [feat] sort-imports rule that is an ESLint workalike (closes #189)

- src/rules/validJsdocRule.ts
- src/test/rules/blockSpacingRuleTests.ts
- src/test/rules/braceStyleRuleTests.ts
- src/test/rules/helper.ts
- src/test/rules/noExtraSemiRuleTests.ts
- src/test/rules/noRegexSpacesRuleTests.ts
- src/test/rules/noSparseArraysRuleTests.ts
- src/test/rules/noUnexpectedMultilineRuleTests.ts
- src/test/rules/objectCurlySpacingRuleTests.ts
- src/test/rules/ruleTester.ts
- src/test/rules/validJsdocRuleTests.ts
- src/test/rules/validTypeofRuleTests.ts
I have updated some rule tests to use the ruleTester. This will allow us to add more tests and modify the rules by making sure that we are obtaining the correct error messages and positions.
There remains about 10 rules to migrate to using the ruleTester.
> [test] Test helper deprecation

- src/rules/sortImportsRule.ts
- src/test/rules/sortImportsRuleTests.ts
I discovered a bug in sorting single imports where one was a substring of the other. e.g.
```typescript
import {Foo} from 'a';
import {Fooz} from 'b'; 
```
Was returning an error. This PR corrects it. I added some more tests to cover other scenarios as well.
> Fix bug in single type imports (Closes #201)

- package.json
- src/rules/terMaxLenRule.ts
- src/rules/validJsdocRule.ts
https://github.com/palantir/tslint/pull/2370 removed the deprecated scanAllTokens and SkippableTokenAwareRuleWalker. That change will be shipped with tslint@5.0.
This PR replaces them with a utility function of `tsutils`.
> Remove usage of deprecated tslint features

- package.json
- tsconfig.json
Using tslib we can avoid duplicating code in each generated file. This
is usually the code for `__extends` among others.
> [perf] removing duplicated generated code

- src/test/rules/helper.ts
- src/test/rules/noConstantConditionRuleTests.ts
- src/test/rules/ruleTester.ts
Upon close inspection on their source code I found out that each
tslint.json raw contents go through the `parseConfigFile` function. The
changes I had made were a very hacky (and ugly) way of creating a
configuration file. This brings us back to the original code and all
tests seem to pass. There is no rush in creating a release for this
since this is for our internal tests.
> [refactor-tests] reverting changes in favor of using tslint parseConfigFile

- index.js
- tslint_eslint_rules.json
tslint recently (today) added the ability to specify installed packages as `rulesDirectory`. To avoid this unnecessary module resolution, this PR makes `rulesDirectory` a relative path.
> Avoid module resolution for rules directory

- src/rules/validJsdocRule.ts
- src/test/rules/validJsdocRuleTests.ts
The start index of the comment was not taking into account
whitespace before the start of the comment.
> [bug] fixed valid-jsdoc rule (closes #220)

- tslint.json
I am not sure if this is considered an issue. But I will go ahead and make a pull request after fixing this.        
$ tslint Version 5.2.0
$ tsc Version 2.3.2
This is an "issue" in tslint.json file. I downloaded the tslint.json file from this repo.  I am using vscode which does not like it (green squiggly line) when **"no-consecutive-blank-lines": true**, when I hovered over, tooltip: "Incorrect type: expected Array. Green squiggly line goes away when I give an Array type: **"no-consecutive-blank-lines": [true]**
These are the rules which are currently having the same "issue"
**- "no-consecutive-blank-lines": [true]**
**- "no-inferrable-types": [false]**
> Changed type to Array[true][false] affecting 2 rules in tslint.json

- CONTRIBUTING.md
- gulpfile.js
- src/readme/rules.ts
- src/tools/newRule.ts
`new-rule` gulp task has been updated to make sure we add the ter
prefix. The templates have also been updated and link to tslint has
been added to point developers on how to design rule walkers.
> [docs] update CONTRIBUTING page to state that rules must have ter prefix

- src/rules/validJsdocRule.ts
- src/test/rules/validJsdocRuleTests.ts
Closes #238 
This fixes the issue, and adds a test for it. The only problem is, the test suite won't actually fail on warnings. It displays the warning, but it won't fail:
Let me know if there is anything I must do to make the test suite fail on the warning.
> [bug] fix null warning in valid-jsdoc

- src/docs/rules/terComputedPropertySpacingRule.md
- src/readme/rules.ts
- src/rules/terComputedPropertySpacingRule.ts
- src/test/rules/terComputedPropertySpacingRuleTests.ts
Adding the `ter-computed-property-spacing` rule, which implements `computed-property-spacing` from eslint.
http://eslint.org/docs/rules/computed-property-spacing
See also #172
> [feat] Implementing ter-computed-property-spacing rule

- package.json
The rule .js files require both tslint and typescript.  However, tslint is a peerDependency while typescript is only a devDependency.  I added it as a peer dependency as well (similar to tslint).  
My build system depends on the package.json specifying a dependency if it is used, so while for others this will usually not be a problem I kindly ask you to please merge it in.
> add peer dependency to typescript

- src/rules/validJsdocRule.ts
- src/test/rules/validJsdocRuleTests.ts
Closes #234.
If a function is declared to have a return type of `void` or `never`, but had a return statement with an expression, the `valid-jsdoc` rule was expecting to find an `@returns` tag in the comments. In the case of `void` and `never` functions, they can't return anything, and the return statement was just a way of calling a function and exiting in the one statement.
The change I've made checks if the function has a declared type, and if that declared type is `void` or `never`, then an `@returns` tag is not required (but is allowed to exist). If the function doesn't have a declared type, or it's not `void` or `never`, then the rule operates exactly as it did before.
> [bug] valid-jsdoc does not require @returns on void or never functions (closes #234)

- .vscode/settings.json
- README.md
- package-lock.json
- src/docs/rules/terNoTabsRule.md
- src/readme/rules.ts
- src/rules/terNoTabsRule.ts
- src/test/rules/terNoTabsRuleTests.ts
Adding `ter-no-tabs` rule, which implements `no-tabs` from ESLint
https://eslint.org/docs/rules/no-tabs
closes #215
part of #251
> [feat] added ter-no-tabs rule (closes #215)

- src/rules/terIndentRule.ts
- src/test/rules/terIndentRuleTests.ts
The call expression may contain a chain of properties, for instance
`this.prop.other.fun(`. Sometimes we like to break these chains so that
the parenthesis start in another line. The indentation should follow
from the indentation on the open parens and not the caller.
> [fix] issue with call expressions (closes #254)

- .vscode/launch.json
- .vscode/tasks.json
The build task was not defined in `tasks.json`
So, running `test` configuration from launch.json shows the following error:
The default `build` task in `tasks.json` fixes it.
Also, the `test` configuration runs all tests - it takes time to hit the breakpoints.
The `single test` configuration runs test for currently opened test file as follows:
> [feat] added default gulp build task and run single test launch config

- src/docs/rules/terNoMixedSpacesAndTabsRule.md
Remove the extra `]` from `ter-no-mixed-spaces-and-tabs` because it only accepts object
> Remove [ from "ter-no-mixed-spaces-and-tabs"

- src/rules/validJsdocRule.ts
- src/test/rules/validJsdocRuleTests.ts
The valid-jsdoc rule currently recognizes `@inheritdoc` as a tag that indicates that a method/property is an override, but it does not recognize the common variant `@inheritDoc`. This PR adds support for recognizing `@inheritDoc`.
> [feat] Enhance valid-jsdoc to recognize @inheritDoc tag as an override

- src/rules/sortImportsRule.ts
- src/test/rules/sortImportsRuleTests.ts
Added two tests which should behave the same. If we do not trim the name then we won't be able to add space on the curly braces.
> [fix] the imported object name was not being trimmed (Closes #319)

- package.json
This should close #332
It updates the `package-json` to allow ts 3.0 as a peer dependency, preventing the following warning:
> warning " > tslint-eslint-rules@5.3.1" has incorrect peer dependency "typescript@^2.2.0".
```diff
"peerDependencies": {
"tslint": "^5.0.0",
-    "typescript": "^2.2.0"
+    "typescript": "^2.2.0 || ^3.0.0"
},
```
> [fix] included typescript 3 in peerDependency version range (closes #332)

- package-lock.json
(text copied from Issue #339)
When I `npm install`ed, the package-json version updated. Perhaps some version bumps were done manually in `package.json` without updating the *lockfile* (as happens automatically with `npm version ____`).
```diff
{
"name": "tslint-eslint-rules",
-  "version": "5.0.0",
+  "version": "5.3.1",
// ...
```
> [fix] update version in package-lock.json (closes #339)
